services:
  cumtb_api:
    image: cumtb_api:latest   # 替换为提供API服务的容器镜像
    container_name: cumtb_api
    restart: unless-stopped
    depends_on:
      - cumtb_redis
      # ports:
      #  - 5000:5000 # 如果需要暴露给宿主机
    networks:
      - cumtb_network
    
  cumtb_redis:
    image: redis:latest
    container_name: cumtb_redis
    restart: unless-stopped
    networks:
      - cumtb_network

  # cumtb_grade:
  #   image: cumtb_grade:latest # 替换为需要访问API服务的容器镜像
  #   container_name: cumtb_grade
  #   restart: unless-stopped
  #   volumes:
  #     - grade_data:/website
  #   ports:
  #     - 2345:80
  #   depends_on:
  #     - cumtb_api
  #   networks:
  #     - cumtb_network

  cumtb_grade_inquire:
    image: cumtb_grade_inquire:0.1.2
    container_name: cumtb_grade_inquire
    restart: unless-stopped
    ports:
      - 8081:80
    depends_on:
      - cumtb_api
    networks:
      - cumtb_network

# volumes:
#   grade_data:

networks:
  cumtb_network:
    driver: bridge
